package at.aau.serg.websocketdemoserver.messaging.dtos;

public enum GameMessageType {
  GAME_STARTED,
  ROLL_DICE,
  MOVE,
  END_TURN,
  ENTER_ROOM,
  TAKE_HIDDEN_WAY,
  MAKE_ACCUSATION,
  MAKE_SUGGESTION,
  SUGGESTION_REQUEST,
  SUGGESTION_RESPONSE,
  SUGGESTION_RESULT,
  SUGGESTION_ERROR,
  GAME_FINISHED,
  GAME_PAUSED,
  CONTINUE_GAME,
  GAME_ABORTED,
  CHEAT_ATTEMPT,
  CHEAT_BUTTON_PRESSED,
  CHEAT_RESULT
}
